apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-minikube
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-minikube
          image: rafarngt/img-nodejs-minikube:v.0.1
          ports:
          - containerPort: 3000